spring.application.name=spyro-backend
server.port=8080

carbon-intensity.base-url=https://api.carbonintensity.org.uk

carbon-intensity.cache-ttl-minutes=30

app.cors.allowed-origins=http://localhost:3000
